- hosts: pve

  tasks:
  - name: create CT
    community.general.proxmox:
      node: pve
      api_user: root@pam
      api_password: 12345678
      api_host: pve
      password: 12345678
      hostname: deb2
      cores: 2
      memory: 1024
      ostemplate: 'local:vztmpl/deb11.tar.gz'
