- hosts: pve

  tasks:
  - name: create CT //Name playbook
    community.general.proxmox:
      node: pve
      api_user: root@pam //User proxmox
      api_password: 12345678 //Password proxmox
      api_host: pve //Host proxmox
      password: 12345678 //Password new system
      hostname: deb2  //Hostname new system
      cores: 2  //Core new system
      memory: 1024 //Memory new system
      ostemplate: 'local:vztmpl/deb11.tar.gz' //Directory snapshot
